apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-app
  namespace: test1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: backend-app
status:
  loadBalancer: {}
