apiVersion: v1
kind: Pod
metadata:
  labels:
    run: env-pod
  name: env-pod
spec:
  containers:
  - image: busybox
    name: env-pod
    command: ["sh", "-c", "printenv && sleep 3600"]
    env:
    - name: APP_ENV
      value: "production"
    - name: APP_VERSION
      value: "v2"
      
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
