apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-pod
  name: secret-pod
spec:
  containers:
  - image: busybox
    name: secret-pod
    command: ["/bin/sh"]
    args: ["-c", "printenv && sleep 3600"]
    envFrom:
      - secretRef:
          name: secret-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
