apiVersion: v1
kind: Pod
metadata:
  labels:
    run: shared-volume-pod
  name: shared-volume-pod
spec:
  containers:
  - image: busybox
    name: shared-volume-pod
    command: ["/bin/sh"]
    args: ['-c', 'while true; do date >> /data/log.txt; sleep 5; done']
    volumeMounts:
    - name: shared-data
      mountPath: /data
  - image: busybox
    name: reader
    command: ["/bin/sh"]
    args: ["-c", "tail -f /logs/log.txt"]
    volumeMounts:
    - name: shared-data
      mountPath: /logs
  volumes:
  - name: shared-data
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
