apiVersion: v1
kind: Pod
metadata:
  labels:
    run: shared-network
  name: shared-network
spec:
  containers:
  - image: nginx
    name: web
    ports:
    - containerPort: 80
  - image: busybox
    name: client
    command: ["/bin/sh"]
    args: ["-c", "while true; do wget -q0- localhost:80; sleep 5; done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
