apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - image: nginx:alpine
    name: multi-pod
  - image: busybox
    name: logger
    command: ["/bin/sh"]
    args: ["-c", 'while true; do echo "logging..."; sleep 5; done']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
