apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sec-pod
  name: sec-pod
spec:
  securityContext:
    runAsUser: 0
    # runAsGroup: 3000
    # fsGroup: 2000
    # runAsNonRoot: true
  containers:
  - image: nicolaka/netshoot
    name: sec-pod
    command: ["sleep", "3600"]
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        # add:
        #   - NET_ADMIN
      privileged: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
