apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app-pod
  name: app-pod
spec:
  containers:
  - image: busybox
    name: app-pod
    command: ["/bin/sh"]
    args: ["-c", "env && sleep 3600"]
    envFrom:
      - configMapRef:
          name: app-config
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
