apiVersion: v1
kind: Pod
metadata:
  labels:
    run: config-pod
  name: config-pod
spec:
  containers:
  - image: busybox
    name: config-pod
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
      - name: app-config
        mountPath: /etc/config
  volumes:
    - name: app-config
      configMap:
        name: app-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
