apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-pod
  name: secret-pod
spec:
  containers:
  - image: busybox
    name: secret-pod
    command: ["/bin/sh"]
    args: ["-c", "env && sleep 3600"]
    volumeMounts:
      - name: secret-mount
        mountPath: /etc/secret
  volumes:
    - name: secret-mount
      secret:
        secretName: db-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
