apiVersion: v1
kind: Pod
metadata:
  name: probe-pod
spec:
  containers:
  - name: app
    image: nginx
    livenessProbe:  # HTTPGet example
      httpGet:
        path: /healthz
        port: 80
        scheme: HTTP  # or HTTPS
        httpHeaders: [{name: Custom-Header, value: Awesome}]
      initialDelaySeconds: 3
      periodSeconds: 3
      timeoutSeconds: 1
      failureThreshold: 3
    readinessProbe:  # Exec example
      exec:
        command: ["cat", "/tmp/healthy"]
      initialDelaySeconds: 5
      periodSeconds: 5
    startupProbe:  # TCP example
      tcpSocket:
        port: 8080
      failureThreshold: 30
      periodSeconds: 10
