apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 3600

    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy

      initialDelaySeconds: 5
      periodSeconds: 5
