apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-pod
  name: busybox-pod
spec:
  containers:
  - image: busybox
    name: busybox-pod
    command: ["/bin/sh"]
    args: ["-c", "touch /tmp/health; sleep 3600"]
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/health
      initialDelaySeconds: 5
      periodSeconds: 5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
