apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: final-exam
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
