apiVersion: v1
kind: Pod
metadata: 
  name: web-pod
  labels:
    app: bai1
spec:
  containers:
  - name: nginx-container
    image: nginx:1.25
    ports:
    - containerPort: 80
  restartPolicy: Always
