apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: container1
    image: busybox
    command: ["sleep", "3600"]

  - name: container2
    image: busybox
    command: ["sleep", "3600"]
