apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: app-pod
spec:
  containers:
  - image: nginx:1.25
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
