apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-deployment
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
