apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
  name: nginx-service-yaml
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
status:
  loadBalancer: {}
