apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web-app
  namespace: exam-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ['sh', '-c', 'sleep 3600']
        resources: {}
status: {}
